// UK Locations Data
export const ukLocations = [
    // England - Major Cities
    { city: "London", region: "England", country: "UK" },
    { city: "Manchester", region: "England", country: "UK" },
    { city: "Birmingham", region: "England", country: "UK" },
    { city: "Liverpool", region: "England", country: "UK" },
    { city: "Leeds", region: "England", country: "UK" },
    { city: "Sheffield", region: "England", country: "UK" },
    { city: "Bristol", region: "England", country: "UK" },
    { city: "Leicester", region: "England", country: "UK" },
    { city: "Coventry", region: "England", country: "UK" },
    { city: "Nottingham", region: "England", country: "UK" },
    { city: "Newcastle upon Tyne", region: "England", country: "UK" },
    { city: "Southampton", region: "England", country: "UK" },
    { city: "Portsmouth", region: "England", country: "UK" },
    { city: "Brighton", region: "England", country: "UK" },
    { city: "Reading", region: "England", country: "UK" },
    { city: "Northampton", region: "England", country: "UK" },
    { city: "Luton", region: "England", country: "UK" },
    { city: "Bolton", region: "England", country: "UK" },
    { city: "Bournemouth", region: "England", country: "UK" },
    { city: "Norwich", region: "England", country: "UK" },
    { city: "Swindon", region: "England", country: "UK" },
    { city: "Southend-on-Sea", region: "England", country: "UK" },
    { city: "Middlesbrough", region: "England", country: "UK" },
    { city: "Peterborough", region: "England", country: "UK" },
    { city: "Cambridge", region: "England", country: "UK" },
    { city: "Oxford", region: "England", country: "UK" },
    { city: "Ipswich", region: "England", country: "UK" },
    { city: "Exeter", region: "England", country: "UK" },
    { city: "Gloucester", region: "England", country: "UK" },
    { city: "York", region: "England", country: "UK" },
    { city: "Plymouth", region: "England", country: "UK" },
    { city: "Blackpool", region: "England", country: "UK" },
    { city: "Huddersfield", region: "England", country: "UK" },
    { city: "Milton Keynes", region: "England", country: "UK" },
    { city: "Derby", region: "England", country: "UK" },
    { city: "Stoke-on-Trent", region: "England", country: "UK" },
    { city: "Wolverhampton", region: "England", country: "UK" },
    { city: "Sunderland", region: "England", country: "UK" },
    { city: "Blackburn", region: "England", country: "UK" },
    { city: "Oldham", region: "England", country: "UK" },
    { city: "Wigan", region: "England", country: "UK" },
    { city: "Rotherham", region: "England", country: "UK" },
    { city: "Warrington", region: "England", country: "UK" },
    { city: "Stockport", region: "England", country: "UK" },
    { city: "Grimsby", region: "England", country: "UK" },
    { city: "Scunthorpe", region: "England", country: "UK" },
    { city: "Doncaster", region: "England", country: "UK" },
    { city: "Barnsley", region: "England", country: "UK" },
    { city: "Wakefield", region: "England", country: "UK" },
    { city: "Huddersfield", region: "England", country: "UK" },
    { city: "Halifax", region: "England", country: "UK" },
    { city: "Bradford", region: "England", country: "UK" },
    { city: "Hull", region: "England", country: "UK" },
    
    // Scotland
    { city: "Edinburgh", region: "Scotland", country: "UK" },
    { city: "Glasgow", region: "Scotland", country: "UK" },
    { city: "Aberdeen", region: "Scotland", country: "UK" },
    { city: "Dundee", region: "Scotland", country: "UK" },
    { city: "Inverness", region: "Scotland", country: "UK" },
    { city: "Perth", region: "Scotland", country: "UK" },
    { city: "Stirling", region: "Scotland", country: "UK" },
    
    // Wales
    { city: "Cardiff", region: "Wales", country: "UK" },
    { city: "Swansea", region: "Wales", country: "UK" },
    { city: "Newport", region: "Wales", country: "UK" },
    { city: "Wrexham", region: "Wales", country: "UK" },
    { city: "Bangor", region: "Wales", country: "UK" },
    
    // Northern Ireland
    { city: "Belfast", region: "Northern Ireland", country: "UK" },
    { city: "Derry", region: "Northern Ireland", country: "UK" },
    { city: "Lisburn", region: "Northern Ireland", country: "UK" },
    { city: "Newry", region: "Northern Ireland", country: "UK" },
  ];
  
  // USA Locations Data
  export const usaLocations = [
    // Major Cities
    { city: "New York", state: "New York", country: "USA" },
    { city: "Los Angeles", state: "California", country: "USA" },
    { city: "Chicago", state: "Illinois", country: "USA" },
    { city: "Houston", state: "Texas", country: "USA" },
    { city: "Phoenix", state: "Arizona", country: "USA" },
    { city: "Philadelphia", state: "Pennsylvania", country: "USA" },
    { city: "San Antonio", state: "Texas", country: "USA" },
    { city: "San Diego", state: "California", country: "USA" },
    { city: "Dallas", state: "Texas", country: "USA" },
    { city: "San Jose", state: "California", country: "USA" },
    { city: "Austin", state: "Texas", country: "USA" },
    { city: "Jacksonville", state: "Florida", country: "USA" },
    { city: "Fort Worth", state: "Texas", country: "USA" },
    { city: "Columbus", state: "Ohio", country: "USA" },
    { city: "Charlotte", state: "North Carolina", country: "USA" },
    { city: "San Francisco", state: "California", country: "USA" },
    { city: "Indianapolis", state: "Indiana", country: "USA" },
    { city: "Seattle", state: "Washington", country: "USA" },
    { city: "Denver", state: "Colorado", country: "USA" },
    { city: "Washington", state: "District of Columbia", country: "USA" },
    { city: "Boston", state: "Massachusetts", country: "USA" },
    { city: "El Paso", state: "Texas", country: "USA" },
    { city: "Nashville", state: "Tennessee", country: "USA" },
    { city: "Detroit", state: "Michigan", country: "USA" },
    { city: "Oklahoma City", state: "Oklahoma", country: "USA" },
    { city: "Portland", state: "Oregon", country: "USA" },
    { city: "Las Vegas", state: "Nevada", country: "USA" },
    { city: "Memphis", state: "Tennessee", country: "USA" },
    { city: "Louisville", state: "Kentucky", country: "USA" },
    { city: "Baltimore", state: "Maryland", country: "USA" },
    { city: "Milwaukee", state: "Wisconsin", country: "USA" },
    { city: "Albuquerque", state: "New Mexico", country: "USA" },
    { city: "Tucson", state: "Arizona", country: "USA" },
    { city: "Fresno", state: "California", country: "USA" },
    { city: "Sacramento", state: "California", country: "USA" },
    { city: "Kansas City", state: "Missouri", country: "USA" },
    { city: "Mesa", state: "Arizona", country: "USA" },
    { city: "Atlanta", state: "Georgia", country: "USA" },
    { city: "Omaha", state: "Nebraska", country: "USA" },
    { city: "Raleigh", state: "North Carolina", country: "USA" },
    { city: "Miami", state: "Florida", country: "USA" },
    { city: "Long Beach", state: "California", country: "USA" },
    { city: "Virginia Beach", state: "Virginia", country: "USA" },
    { city: "Oakland", state: "California", country: "USA" },
    { city: "Minneapolis", state: "Minnesota", country: "USA" },
    { city: "Tulsa", state: "Oklahoma", country: "USA" },
    { city: "Tampa", state: "Florida", country: "USA" },
    { city: "Arlington", state: "Texas", country: "USA" },
    { city: "New Orleans", state: "Louisiana", country: "USA" },
    { city: "Wichita", state: "Kansas", country: "USA" },
    { city: "Cleveland", state: "Ohio", country: "USA" },
    { city: "Tampa", state: "Florida", country: "USA" },
    { city: "Bakersfield", state: "California", country: "USA" },
    { city: "Aurora", state: "Colorado", country: "USA" },
    { city: "Honolulu", state: "Hawaii", country: "USA" },
    { city: "Anaheim", state: "California", country: "USA" },
    { city: "Santa Ana", state: "California", country: "USA" },
    { city: "St. Louis", state: "Missouri", country: "USA" },
    { city: "Riverside", state: "California", country: "USA" },
    { city: "Corpus Christi", state: "Texas", country: "USA" },
    { city: "Lexington", state: "Kentucky", country: "USA" },
    { city: "Henderson", state: "Nevada", country: "USA" },
    { city: "Stockton", state: "California", country: "USA" },
    { city: "Saint Paul", state: "Minnesota", country: "USA" },
    { city: "Cincinnati", state: "Ohio", country: "USA" },
    { city: "St. Petersburg", state: "Florida", country: "USA" },
    { city: "Pittsburgh", state: "Pennsylvania", country: "USA" },
    { city: "Greensboro", state: "North Carolina", country: "USA" },
    { city: "Lincoln", state: "Nebraska", country: "USA" },
    { city: "Plano", state: "Texas", country: "USA" },
    { city: "Anchorage", state: "Alaska", country: "USA" },
    { city: "Baton Rouge", state: "Louisiana", country: "USA" },
    { city: "Jersey City", state: "New Jersey", country: "USA" },
    { city: "Durham", state: "North Carolina", country: "USA" },
    { city: "Buffalo", state: "New York", country: "USA" },
    { city: "North Las Vegas", state: "Nevada", country: "USA" },
    { city: "Reno", state: "Nevada", country: "USA" },
    { city: "Fort Wayne", state: "Indiana", country: "USA" },
    { city: "Orlando", state: "Florida", country: "USA" },
    { city: "St. Petersburg", state: "Florida", country: "USA" },
    { city: "Chandler", state: "Arizona", country: "USA" },
    { city: "Laredo", state: "Texas", country: "USA" },
    { city: "Norfolk", state: "Virginia", country: "USA" },
    { city: "Garland", state: "Texas", country: "USA" },
    { city: "Madison", state: "Wisconsin", country: "USA" },
    { city: "Glendale", state: "Arizona", country: "USA" },
    { city: "Hialeah", state: "Florida", country: "USA" },
    { city: "Raleigh", state: "North Carolina", country: "USA" },
    { city: "Scottsdale", state: "Arizona", country: "USA" },
    { city: "Irving", state: "Texas", country: "USA" },
    { city: "Chesapeake", state: "Virginia", country: "USA" },
    { city: "Gilbert", state: "Arizona", country: "USA" },
    { city: "Fremont", state: "California", country: "USA" },
    { city: "Boise", state: "Idaho", country: "USA" },
    { city: "Richmond", state: "Virginia", country: "USA" },
    { city: "Birmingham", state: "Alabama", country: "USA" },
    { city: "Spokane", state: "Washington", country: "USA" },
    { city: "Rochester", state: "New York", country: "USA" },
    { city: "Des Moines", state: "Iowa", country: "USA" },
    { city: "Modesto", state: "California", country: "USA" },
    { city: "Fayetteville", state: "North Carolina", country: "USA" },
    { city: "Tacoma", state: "Washington", country: "USA" },
    { city: "Oxnard", state: "California", country: "USA" },
    { city: "Fontana", state: "California", country: "USA" },
    { city: "Columbus", state: "Georgia", country: "USA" },
    { city: "Montgomery", state: "Alabama", country: "USA" },
    { city: "Moreno Valley", state: "California", country: "USA" },
    { city: "Shreveport", state: "Louisiana", country: "USA" },
    { city: "Aurora", state: "Illinois", country: "USA" },
    { city: "Yonkers", state: "New York", country: "USA" },
    { city: "Akron", state: "Ohio", country: "USA" },
    { city: "Huntington Beach", state: "California", country: "USA" },
    { city: "Little Rock", state: "Arkansas", country: "USA" },
    { city: "Augusta", state: "Georgia", country: "USA" },
    { city: "Amarillo", state: "Texas", country: "USA" },
    { city: "Glendale", state: "California", country: "USA" },
    { city: "Mobile", state: "Alabama", country: "USA" },
    { city: "Grand Rapids", state: "Michigan", country: "USA" },
    { city: "Salt Lake City", state: "Utah", country: "USA" },
    { city: "Tallahassee", state: "Florida", country: "USA" },
    { city: "Huntsville", state: "Alabama", country: "USA" },
    { city: "Grand Prairie", state: "Texas", country: "USA" },
    { city: "Knoxville", state: "Tennessee", country: "USA" },
    { city: "Worcester", state: "Massachusetts", country: "USA" },
    { city: "Newport News", state: "Virginia", country: "USA" },
    { city: "Brownsville", state: "Texas", country: "USA" },
    { city: "Overland Park", state: "Kansas", country: "USA" },
    { city: "Santa Clarita", state: "California", country: "USA" },
    { city: "Providence", state: "Rhode Island", country: "USA" },
    { city: "Garden Grove", state: "California", country: "USA" },
    { city: "Chattanooga", state: "Tennessee", country: "USA" },
    { city: "Oceanside", state: "California", country: "USA" },
    { city: "Jackson", state: "Mississippi", country: "USA" },
    { city: "Fort Lauderdale", state: "Florida", country: "USA" },
    { city: "Santa Rosa", state: "California", country: "USA" },
    { city: "Rancho Cucamonga", state: "California", country: "USA" },
    { city: "Port St. Lucie", state: "Florida", country: "USA" },
    { city: "Tempe", state: "Arizona", country: "USA" },
    { city: "Ontario", state: "California", country: "USA" },
    { city: "Vancouver", state: "Washington", country: "USA" },
    { city: "Sioux Falls", state: "South Dakota", country: "USA" },
    { city: "Peoria", state: "Arizona", country: "USA" },
    { city: "Salem", state: "Oregon", country: "USA" },
    { city: "Elk Grove", state: "California", country: "USA" },
    { city: "Corona", state: "California", country: "USA" },
    { city: "Eugene", state: "Oregon", country: "USA" },
    { city: "Pembroke Pines", state: "Florida", country: "USA" },
    { city: "Salem", state: "Massachusetts", country: "USA" },
    { city: "Lancaster", state: "California", country: "USA" },
    { city: "Frisco", state: "Texas", country: "USA" },
    { city: "Cary", state: "North Carolina", country: "USA" },
    { city: "Hayward", state: "California", country: "USA" },
    { city: "Palmdale", state: "California", country: "USA" },
    { city: "Alexandria", state: "Virginia", country: "USA" },
    { city: "Lakewood", state: "Colorado", country: "USA" },
    { city: "Springfield", state: "Missouri", country: "USA" },
    { city: "Pasadena", state: "California", country: "USA" },
    { city: "Sunnyvale", state: "California", country: "USA" },
    { city: "Macon", state: "Georgia", country: "USA" },
    { city: "Pomona", state: "California", country: "USA" },
    { city: "Hollywood", state: "Florida", country: "USA" },
    { city: "Kansas City", state: "Kansas", country: "USA" },
    { city: "Joliet", state: "Illinois", country: "USA" },
    { city: "Torrance", state: "California", country: "USA" },
    { city: "Bridgeport", state: "Connecticut", country: "USA" },
    { city: "Paterson", state: "New Jersey", country: "USA" },
    { city: "Naperville", state: "Illinois", country: "USA" },
    { city: "Savannah", state: "Georgia", country: "USA" },
    { city: "Mesquite", state: "Texas", country: "USA" },
    { city: "Syracuse", state: "New York", country: "USA" },
    { city: "McAllen", state: "Texas", country: "USA" },
    { city: "Pasadena", state: "Texas", country: "USA" },
    { city: "Orange", state: "California", country: "USA" },
    { city: "Fullerton", state: "California", country: "USA" },
    { city: "Killeen", state: "Texas", country: "USA" },
    { city: "Dayton", state: "Ohio", country: "USA" },
    { city: "Miramar", state: "Florida", country: "USA" },
    { city: "Hampton", state: "Virginia", country: "USA" },
    { city: "Warren", state: "Michigan", country: "USA" },
    { city: "Bellevue", state: "Washington", country: "USA" },
    { city: "West Valley City", state: "Utah", country: "USA" },
    { city: "Columbia", state: "South Carolina", country: "USA" },
    { city: "Olathe", state: "Kansas", country: "USA" },
    { city: "Sterling Heights", state: "Michigan", country: "USA" },
    { city: "New Haven", state: "Connecticut", country: "USA" },
    { city: "Topeka", state: "Kansas", country: "USA" },
    { city: "Thousand Oaks", state: "California", country: "USA" },
    { city: "Cedar Rapids", state: "Iowa", country: "USA" },
    { city: "Visalia", state: "California", country: "USA" },
    { city: "Elizabeth", state: "New Jersey", country: "USA" },
    { city: "Gainesville", state: "Florida", country: "USA" },
    { city: "Simi Valley", state: "California", country: "USA" },
    { city: "Stamford", state: "Connecticut", country: "USA" },
    { city: "Hartford", state: "Connecticut", country: "USA" },
    { city: "Concord", state: "California", country: "USA" },
    { city: "Kent", state: "Washington", country: "USA" },
    { city: "Lafayette", state: "Louisiana", country: "USA" },
    { city: "Midland", state: "Texas", country: "USA" },
    { city: "Surprise", state: "Arizona", country: "USA" },
    { city: "Denton", state: "Texas", country: "USA" },
    { city: "Victorville", state: "California", country: "USA" },
    { city: "Evansville", state: "Indiana", country: "USA" },
    { city: "Santa Clara", state: "California", country: "USA" },
    { city: "Abilene", state: "Texas", country: "USA" },
    { city: "Athens", state: "Georgia", country: "USA" },
    { city: "Vallejo", state: "California", country: "USA" },
    { city: "Allentown", state: "Pennsylvania", country: "USA" },
    { city: "Norman", state: "Oklahoma", country: "USA" },
    { city: "Beaumont", state: "Texas", country: "USA" },
    { city: "Independence", state: "Missouri", country: "USA" },
    { city: "Murfreesboro", state: "Tennessee", country: "USA" },
    { city: "Ann Arbor", state: "Michigan", country: "USA" },
    { city: "Springfield", state: "Illinois", country: "USA" },
    { city: "Berkeley", state: "California", country: "USA" },
    { city: "Peoria", state: "Illinois", country: "USA" },
    { city: "Provo", state: "Utah", country: "USA" },
    { city: "El Monte", state: "California", country: "USA" },
    { city: "Columbia", state: "Missouri", country: "USA" },
    { city: "Lansing", state: "Michigan", country: "USA" },
    { city: "Fargo", state: "North Dakota", country: "USA" },
    { city: "Downey", state: "California", country: "USA" },
    { city: "Costa Mesa", state: "California", country: "USA" },
    { city: "Wilmington", state: "North Carolina", country: "USA" },
    { city: "Arvada", state: "Colorado", country: "USA" },
    { city: "Inglewood", state: "California", country: "USA" },
    { city: "Miami Gardens", state: "Florida", country: "USA" },
    { city: "Carlsbad", state: "California", country: "USA" },
    { city: "Westminster", state: "Colorado", country: "USA" },
    { city: "Rochester", state: "Minnesota", country: "USA" },
    { city: "Odessa", state: "Texas", country: "USA" },
    { city: "Manchester", state: "New Hampshire", country: "USA" },
    { city: "Elgin", state: "Illinois", country: "USA" },
    { city: "West Jordan", state: "Utah", country: "USA" },
    { city: "Round Rock", state: "Texas", country: "USA" },
    { city: "Clearwater", state: "Florida", country: "USA" },
    { city: "Waterbury", state: "Connecticut", country: "USA" },
    { city: "Gresham", state: "Oregon", country: "USA" },
    { city: "Fairfield", state: "California", country: "USA" },
    { city: "Billings", state: "Montana", country: "USA" },
    { city: "Lowell", state: "Massachusetts", country: "USA" },
    { city: "San Buenaventura", state: "California", country: "USA" },
    { city: "Pueblo", state: "Colorado", country: "USA" },
    { city: "High Point", state: "North Carolina", country: "USA" },
    { city: "West Covina", state: "California", country: "USA" },
    { city: "Richmond", state: "California", country: "USA" },
    { city: "Murrieta", state: "California", country: "USA" },
    { city: "Cambridge", state: "Massachusetts", country: "USA" },
    { city: "Antioch", state: "California", country: "USA" },
    { city: "Temecula", state: "California", country: "USA" },
    { city: "Norwalk", state: "California", country: "USA" },
    { city: "Daly City", state: "California", country: "USA" },
    { city: "Burbank", state: "California", country: "USA" },
    { city: "Santa Maria", state: "California", country: "USA" },
    { city: "El Cajon", state: "California", country: "USA" },
    { city: "San Mateo", state: "California", country: "USA" },
    { city: "Lewisville", state: "Texas", country: "USA" },
    { city: "South Bend", state: "Indiana", country: "USA" },
    { city: "Lakeland", state: "Florida", country: "USA" },
    { city: "Erie", state: "Pennsylvania", country: "USA" },
    { city: "Tyler", state: "Texas", country: "USA" },
    { city: "Pearland", state: "Texas", country: "USA" },
    { city: "College Station", state: "Texas", country: "USA" },
    { city: "Kenosha", state: "Wisconsin", country: "USA" },
    { city: "Sandy Springs", state: "Georgia", country: "USA" },
    { city: "Clovis", state: "California", country: "USA" },
    { city: "Flint", state: "Michigan", country: "USA" },
    { city: "Roanoke", state: "Virginia", country: "USA" },
    { city: "Albany", state: "New York", country: "USA" },
    { city: "Jurupa Valley", state: "California", country: "USA" },
    { city: "Compton", state: "California", country: "USA" },
    { city: "San Angelo", state: "Texas", country: "USA" },
    { city: "Hillsboro", state: "Oregon", country: "USA" },
    { city: "Lawton", state: "Oklahoma", country: "USA" },
    { city: "Renton", state: "Washington", country: "USA" },
    { city: "Vista", state: "California", country: "USA" },
    { city: "Davie", state: "Florida", country: "USA" },
    { city: "Greeley", state: "Colorado", country: "USA" },
    { city: "Mission Viejo", state: "California", country: "USA" },
    { city: "Portsmouth", state: "Virginia", country: "USA" },
    { city: "Dearborn", state: "Michigan", country: "USA" },
    { city: "South Gate", state: "California", country: "USA" },
    { city: "Tuscaloosa", state: "Alabama", country: "USA" },
    { city: "Livonia", state: "Michigan", country: "USA" },
    { city: "New Bedford", state: "Massachusetts", country: "USA" },
    { city: "Vacaville", state: "California", country: "USA" },
    { city: "Brockton", state: "Massachusetts", country: "USA" },
    { city: "Roswell", state: "Georgia", country: "USA" },
    { city: "Beaverton", state: "Oregon", country: "USA" },
    { city: "Quincy", state: "Massachusetts", country: "USA" },
    { city: "Sparks", state: "Nevada", country: "USA" },
    { city: "Yakima", state: "Washington", country: "USA" },
    { city: "Lee's Summit", state: "Missouri", country: "USA" },
    { city: "Federal Way", state: "Washington", country: "USA" },
    { city: "Carson", state: "California", country: "USA" },
    { city: "Santa Monica", state: "California", country: "USA" },
    { city: "Hesperia", state: "California", country: "USA" },
    { city: "Allen", state: "Texas", country: "USA" },
    { city: "Rio Rancho", state: "New Mexico", country: "USA" },
    { city: "Yuma", state: "Arizona", country: "USA" },
    { city: "Westminster", state: "California", country: "USA" },
    { city: "Orem", state: "Utah", country: "USA" },
    { city: "Lynn", state: "Massachusetts", country: "USA" },
    { city: "Redding", state: "California", country: "USA" },
    { city: "Spokane Valley", state: "Washington", country: "USA" },
    { city: "Miami Beach", state: "Florida", country: "USA" },
    { city: "League City", state: "Texas", country: "USA" },
    { city: "Lawrence", state: "Kansas", country: "USA" },
    { city: "Santa Barbara", state: "California", country: "USA" },
    { city: "Plantation", state: "Florida", country: "USA" },
    { city: "Sandy", state: "Utah", country: "USA" },
    { city: "Sunrise", state: "Florida", country: "USA" },
    { city: "Macon", state: "Georgia", country: "USA" },
    { city: "Longmont", state: "Colorado", country: "USA" },
    { city: "Boca Raton", state: "Florida", country: "USA" },
    { city: "San Leandro", state: "California", country: "USA" },
    { city: "Hemet", state: "California", country: "USA" },
    { city: "Lakewood", state: "New Jersey", country: "USA" },
    { city: "Meridian", state: "Idaho", country: "USA" },
    { city: "Menifee", state: "California", country: "USA" },
    { city: "Joliet", state: "Illinois", country: "USA" },
    { city: "Chula Vista", state: "California", country: "USA" },
    { city: "Houma", state: "Louisiana", country: "USA" },
    { city: "Suffolk", state: "Virginia", country: "USA" },
    { city: "Florence", state: "South Carolina", country: "USA" },
    { city: "Lakeland", state: "Florida", country: "USA" },
    { city: "Turlock", state: "California", country: "USA" },
    { city: "Mishawaka", state: "Indiana", country: "USA" },
    { city: "Marietta", state: "Georgia", country: "USA" },
    { city: "Bremerton", state: "Washington", country: "USA" },
    { city: "Albany", state: "Georgia", country: "USA" },
    { city: "San Marcos", state: "Texas", country: "USA" },
    { city: "Schaumburg", state: "Illinois", country: "USA" },
    { city: "Great Falls", state: "Montana", country: "USA" },
    { city: "Pembroke Pines", state: "Florida", country: "USA" },
    { city: "Largo", state: "Florida", country: "USA" },
    { city: "Cape Coral", state: "Florida", country: "USA" },
    { city: "Deltona", state: "Florida", country: "USA" },
    { city: "Evanston", state: "Illinois", country: "USA" },
    { city: "Nampa", state: "Idaho", country: "USA" },
    { city: "Hammond", state: "Indiana", country: "USA" },
    { city: "Fayetteville", state: "Arkansas", country: "USA" },
    { city: "Bloomington", state: "Illinois", country: "USA" },
    { city: "Avondale", state: "Arizona", country: "USA" },
    { city: "Perris", state: "California", country: "USA" },
    { city: "Pine Hills", state: "Florida", country: "USA" },
    { city: "Southaven", state: "Mississippi", country: "USA" },
    { city: "Blaine", state: "Minnesota", country: "USA" },
    { city: "Springfield", state: "Ohio", country: "USA" },
    { city: "Pflugerville", state: "Texas", country: "USA" },
    { city: "West Allis", state: "Wisconsin", country: "USA" },
    { city: "West Haven", state: "Connecticut", country: "USA" },
    { city: "Petaluma", state: "California", country: "USA" },
    { city: "St. Clair Shores", state: "Michigan", country: "USA" },
    { city: "Fairburn", state: "Georgia", country: "USA" },
    { city: "West Des Moines", state: "Iowa", country: "USA" },
  ]